### ISSUE TITLE
Crash upon play with no playfield

### ISSUE THREAD

**Issue by MalteRichert** [Rex2002/sound-shapes#27]
On timeSignature branch:
When pressing play with no playfield present I consistently encounter the following exception:
```
Exception in thread "main" java.lang.NullPointerException: Cannot load from object array because "soundMatrix" is null
	at de.dhbw.music.MidiAdapter.tickMidi(MidiAdapter.java:36)
	at de.dhbw.Main.runController(Main.java:132)
	at de.dhbw.Main.main(Main.java:26)
```
@Rex2002 any idea how recent changes might have lead to this? I'm not sure when I last tested without a playfield.

**Comment by Rex2002** [comment]
05dae04 should fix this by adding null-check between adding the metronome-sounds to the MidiBatchMessage and the sound-matrix processing
